# Generated by Django 3.2.8 on 2021-10-15 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('uid', models.IntegerField(unique=True)),
                ('cover', models.URLField(max_length=300)),
                ('link_to_manga', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True)),
                ('number', models.FloatField()),
                ('cover', models.URLField(max_length=300)),
                ('link_to_manga', models.URLField()),
                ('manga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas.manga')),
            ],
        ),
    ]
