# Generated by Django 3.2.8 on 2021-10-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('uid', 'number'), name='unique_chapters'),
        ),
    ]
