# Generated by Django 3.2.8 on 2021-10-15 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0002_chapter_unique_chapters'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('uid', 'number')},
        ),
    ]
