# Generated by Django 3.2.8 on 2021-10-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0003_alter_chapter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='uid',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
    ]
